#!/usr/bin/env sh

# Make sure your XDG paths are set before running this

# TODO: make idempotent, interactive
# TODO: move old config/local into new location

ln -sfv $PWD/config/zsh/zshenv $HOME/.zshenv
source $HOME/.zshenv

# setup config home
mv $HOME/.config $HOME/config.old
ln -sfv "$PWD"/config "$XDG_CONFIG_HOME"
source "$XDG_CONFIG_HOME"/zsh/zprofile

# setup local home
mv "$HOME"/.local "$HOME/local.old"
ln -sfv "$PWD"/local "$HOME/.local"

# ensure dirs exist
mkdir -p "$XDG_DATA_HOME"
mkdir -p "$XDG_CACHE_HOME"
mkdir -p "$XDG_STATE_HOME"

# Install plugin managers
# curl -fLo "$XDG_CONFIG_HOME"/vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# git clone https://github.com/tmux-plugins/tpm "$XDG_CONFIG_HOME"/tmux/plugins/tpm

# "$XDG_CONFIG_HOME"/tmux/plugins/tpm/bin/install_plugins
# TODO - install vim plugins dynamically
