#!/usr/bin/env sh

# TODO - make idempotent, interactive?

# mv $HOME/.local $HOME/.config.old
ln -sfv $PWD/config ${XDG_CONFIG_HOME:-$HOME}/.config
ln -sfv $PWD/config/zsh/zshenv $HOME/.zshenv

# mv $HOME/.local $HOME/.local.old
ln -sfv $PWD/local $HOME/.local
mkdir -p "${XDG_DATA_HOME}"
mkdir -p "${XDG_STATE_HOME}"

# Install plugin managers
curl -fLo ~/.config/vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm

# TODO - install plugins dynamically?
# ~/.tmux/plugins/tpm/bin/install_plugins
