[[ $- != *i* ]] && return

# Load Common Aliases and Functions
if [[ -f "$XDG_CONFIG_HOME"/shell/aliases ]]; then
    source "$XDG_CONFIG_HOME/shell/aliases"
fi


# -----------------------------------------------------------------------------
# > bash options
# -----------------------------------------------------------------------------

shopt -s cdspell
shopt -s cmdhist
shopt -s histappend
shopt -s nocaseglob
shopt -s checkwinsize

export HISTFILESIZE=50000
export HISTSIZE=50000
export HISTCONTROL=ignoreboth:erasedups
export HISTIGNORE='ls:ll:bg:fg:history'
export HISTTIMEFORMAT='%F %T '

export PS1='$( [ $? -eq 0 ] && echo "●" || echo "○" ) \W \$ '

# -----------------------------------------------------------------------------
# > Initialization
# -----------------------------------------------------------------------------

# Load local settings
if [[ -f ~/.bashrc.local ]]; then
    source ~/.bashrc.local
fi
