#!usr/bin/env bash
# Color theme adapated from https://github.com/sonph/onehalf

# Primary
col_bg='#fafafa'
col_fg='#383a42'

# Secondary
col_bg_sec='#e5e5e5'
col_fg_sec='#383a42'

# Inactive background
col_bg_in='#f5f5f5'

# Normal
col_black='#383a42'
col_red='#e45649'
col_green='#50a14f'
col_yellow='#c18401'
col_blue='#0184bc'
col_magenta='#a626a4'
col_cyan='#0997b3'
col_white='#fafafa'
col_gray='#282c34'

# Bright
col_black_b='#383a42'
col_red_b='#e45649'
col_green_b='#50a14f'
col_yellow_b='#c18401'
col_blue_b='#0184bc'
col_magenta_b='#a626a4'
col_cyan_b='#0997b3'
col_white_b='#fafafa'

# Theme colors defaults
pri_bg="$col_gray"
pri_fg="$col_white"
pri_bg_xt='232'
pri_fg_xt='255'

