brew "coreutils"
brew "exiftool"
brew "ffmpeg"
brew "fzf"
brew "htop"
brew "imagemagick"
brew "jq"
brew "pandoc"
brew "ripgrep"
# brew "texlive"
brew "tmux"
brew "tree"
brew "uv"
brew "yt-dlp"

# cask "adobe-digital-editions"
# cask "brewlet"
cask "calibre"
cask "gimp"
cask "google-chrome"
cask "iina"
cask "inkscape"
# cask "kid3"
# cask "miniconda"
# cask "musescore"
# cask "openemu"
# cask "discord"
# cask "sf-symbols"
# cask "steam"
cask "visual-studio-code"
cask "zotero"

# Download through app store when possible:
# AdGuard for Safari, Hush
# WhatSApp
# Slack
# Reeder 5
