# Only the essential packages

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "tmux"
brew "neovim"
cask "iterm2"
# Install these with the app store:
# cask "1Password"
# mas "AdGuard for Safari", id=1440147259

brew "coreutils"
brew "fzf"
brew "htop"
brew "jq"
brew "ripgrep"
brew "tree"

cask "brewlet"
cask "google-cloud-sdk"
cask "miniconda"
cask "zoom"
cask "zotero"
