#!/usr/bin/env zsh
# .zprofile is only loaded for login shells

export PATH="$HOME/.local/bin:$PATH"

if [[ -x $(command -v nvim) ]]; then
    export EDITOR="nvim"
elif [[ -x $(command -v vim) ]]; then
    export EDITOR="vim"
else
    export EDITOR="vi"
fi

# > XDG support

# Main paths

# vim
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'

# less
export LESSHISTFILE="${XDG_CONFIG_HOME}/less/history"
export LESSKEY="${XDG_CONFIG_HOME}/less/keys"

# jupyter
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME"/jupyter

# dircolors
eval $(dircolors "$XDG_CONFIG_HOME"/dircolors/dircolors)


# > Misc apps

export HOMEBREW_NO_ANALYTICS=1


# > Load local config

if [[ -f "$XDG_CONFIG_HOME"/zsh/zprofile.local ]]; then
    source "$XDG_CONFIG_HOME"/zsh/zprofile.local
fi
