#!/usr/bin/env zsh
# .zprofile is only loaded for login shells

if [[ -x $(command -v vim) ]]; then
    export EDITOR="vim"
else
    export EDITOR="vi"
fi

# > XDG support

# vim
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'

export HOMEBREW_NO_ANALYTICS=1

# add XDG bin to PATH
export PATH="$XDG_BIN_HOME:$PATH"

# less
export LESSHISTFILE="${XDG_CONFIG_HOME}/less/history"
export LESSKEY="${XDG_CONFIG_HOME}/less/keys"

# jupyter
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME"/jupyter

# dircolors
# eval $(dircolors "$XDG_CONFIG_HOME"/dircolors/dircolors)

export INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"
export CONDARC="$XDG_CONFIG_HOME/conda/condarc"

# > Load local config

if [[ -f "$XDG_CONFIG_HOME"/zsh/zprofile.local ]]; then
    source "$XDG_CONFIG_HOME"/zsh/zprofile.local
fi