# https://unix.stackexchange.com/questions/547/make-my-zsh-prompt-show-mode-in-vi-mode
# https://zsh.sourceforge.io/Doc/Release/User-Contributions.html#Version-Control-Information
# https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html#Conditional-Substrings-in-Prompts

# Load Common Aliases and Functions
if [[ -f "$XDG_CONFIG_HOME"/shell/aliases ]]; then
    source "$XDG_CONFIG_HOME/shell/aliases"
fi


# -----------------------------------------------------------------------------
# > zsh options
# -----------------------------------------------------------------------------

setopt autocd
setopt correct

# History (see `man zshoptions`)
setopt append_history
setopt share_history
setopt inc_append_history
setopt hist_ignore_all_dups
setopt hist_ignore_space
export HISTSIZE=50000  # the number of items for the internal history list
export SAVEHIST=50000  # maximum number of items for the history file
export HISTFILE="${XDG_STATE_HOME:=$HOME/.local/state}/zsh/history"
mkdir -p "$(dirname "$HISTFILE")"

# Completion
zmodload -i zsh/complist
autoload -Uz compinit
compinit

# Move via words like bash
autoload -U select-word-style
select-word-style bash


# -----------------------------------------------------------------------------
# > Key bindings (Vi Mode with Emacs insertion)
# -----------------------------------------------------------------------------
# Look at `man zshzle` and `bindkey -l` and `zle -al`

bindkey -v
bindkey -M viins "^D" delete-char
bindkey -M viins "^H" backward-delete-char
bindkey -M viins "^A" beginning-of-line
bindkey -M viins "^E" end-of-line
bindkey -M viins "^F" forward-char
bindkey -M viins "^B" backward-char
bindkey -M viins "^P" history-search-backward
bindkey -M viins "^N" history-search-forward
bindkey -M viins "^K" kill-line
bindkey -M viins "^U" backward-kill-line
bindkey -M viins "^R" history-incremental-search-backward

# -----------------------------------------------------------------------------
# > Prompt & VCS
# -----------------------------------------------------------------------------

autoload -U vcs_info
autoload -Uz add-zsh-hook

# Git settings
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git*' formats " [%r-%b]%u%c"
zstyle ':vcs_info:*' check-for-staged-changes true

vcs_precmd() {
    vcs_info
    psvar[1]="${vcs_info_msg_0_} "
}
add-zsh-hook precmd vcs_precmd

conda_precmd() {
    psvar[2]=""
    if [[ -n "$CONDA_PREFIX" ]]; then
        # psvar[2]=" ($(basename $CONDA_PREFIX))"
        psvar[2]=" %F{green}($(basename $CONDA_PREFIX))%f"
    fi
}
add-zsh-hook precmd conda_precmd

# Vi Mode Indicator (Right Prompt)
function zle-line-init zle-keymap-select {
    RPS1="${${KEYMAP/vicmd/%F{red\}█%f}/(main|viins)/}"
    zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select

export PS1="%(?.●.○)%2v%1v%2~ %# "


# -----------------------------------------------------------------------------
# > Custom initializations
# -----------------------------------------------------------------------------

# Load local settings
if [[ -f "$XDG_CONFIG_HOME"/zsh/zshrc.local ]]; then
    source "$XDG_CONFIG_HOME"/zsh/zshrc.local
fi
